### ISSUE TITLE
Update Github Actions to build and release forge

### ISSUE THREAD

**Issue by jamesfwood** [podaac/forge#2]

**Comment by jonathansmolenski** [comment]
I'm setting this to blocked because of the dependency on cae-artifactory packages (the new packages exist in github, the build sources just need to be updated I think?)

Namely, the cumulus-message-adapter needs to be pulled from here: https://mvnrepository.com/artifact/gov.nasa.earthdata/cumulus-message-adapter/1.2.0 Instead of from cae-artifactory.

**Comment by jamesfwood** [comment]
Now working.  Thanks @jonathansmolenski !
